services:
  tms:
    build: .
    ports:
      - "${TMS_HOST_PORT}:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - postgres
  postgres:
    image: 'postgres:14.15'
    container_name: tms_postgres
    environment:
      - POSTGRES_DB=${TMS_DB_NAME}
      - POSTGRES_USER=${TMS_DB_USER}
      - POSTGRES_PASSWORD=${TMS_DB_PASSWORD}
    ports:
      - "${TMS_DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: