spring:
  application:
    name: TaskManagementSystem
  devtools:
    restart:
      enabled: false
  datasource:
    url: jdbc:postgresql://${TMS_HOST_NAME}:${TMS_DB_PORT}/${TMS_DB_NAME}
    username: ${TMS_DB_USER}
    password: ${TMS_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    url: jdbc:postgresql://${TMS_HOST_NAME}:${TMS_DB_PORT}/${TMS_DB_NAME}
    user: ${TMS_DB_USER}
    password: ${TMS_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
jwt:
  secret: jOu4scZUwu34BLGxZQWXAakYRVb62dyRi8tMC66wAlA=
  lifetime: 3600
  refreshLifetime: 3600